### ISSUE TITLE
QA - Subscription - Few changes in the subscription plan pages

### ISSUE THREAD

**Issue by brgurur** [FlowzPlatform/flowz-product-#107]
Please refer the screen shots for the changes in the subscription plan page

![home page dashboard](https://user-images.githubusercontent.com/34448885/36639590-8c5779dc-1a35-11e8-8073-9a91edae85cd.jpg)

**Comment by chiragob** [comment]
all data are dynamically loaded. when we change or create plan it will update in subscription list

**Comment by qajha** [comment]
When super admin changes so they edit the subscription plan and changes somethings.
