### ISSUE TITLE
QA - Dashboard - User Should be Redirect on My Plan Screen After Purchase the Subscription.

### ISSUE THREAD

**Issue by Nikunj025** [FlowzPlatform/flowz-product-#174]
QA - Dashboard - User Should be Redirect on My Plan Screen After Purchase the Subscription.

Test Scenarios
**************
1. If User Pay the Amount for the Subscription then it will be able to Perform task in Dash board.
2. If User Pay the Amount Successfully then Success Message Should be display on the Screen.
3. If User Pay the Amount Successfully then User should be redirect on My Plan Screen and User can able to see their Purchased Plan in My Plan List.

**Comment by Zalasanjay** [comment]
Done and working, moved to staging.
