### ISSUE TITLE
description improper

### ISSUE THREAD

**Issue by emp005169** [FlowzPlatform/flowz-product-#23]
Vmail -  This is a user friendly (vue based) email client. It can receive the email, list it and show the content. It can also send mail in plain or html format to multiple users in an effective and efficient way.
Web Builder - space after full stop.
Accounting - incorrectly copied from MoM text. (take from paul)

**Comment by uhirani78** [comment]
Please provide me proper description of all the app.

**Comment by emp005169** [comment]
see my first comment above. already provided.
