### ISSUE TITLE
QA-Create Plan-When we create the multiple subscription then alignment problem in subscription page refer attachment.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/flowz-product-#55]
When we create the multiple subscription then alignment problem in subscription page refer attachment.
![create plan design issue](https://user-images.githubusercontent.com/36195435/36370168-15b25348-1584-11e8-9493-97ca1241a1bc.png)

**Comment by chiragob** [comment]
UI changed

**Comment by qajha** [comment]
Issue is resolved now as per new UI change
