### ISSUE TITLE
QA-CRM-Subscription-When one user linked with any one subscription and admin user have decide to delete the plan then system is not restrict to user for doing operation

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/flowz-product-#62]

**Comment by chiragob** [comment]
its not a bug Subscription plan and subscribed plan both are different entity. 
for e.g any mobile operator give 1GB internet plan after sometime he update to 2GB so subscribe user not getting 2GB they have to buy again then they will get 2GB.

**Comment by qajha** [comment]
As per developer comment I have closed this Issue
