### ISSUE TITLE
QA-Create Plan-Suggestion-When user subscribes the same plan in multiple times then system do not the restrict the user for buying same plan

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/flowz-product-#64]
When user subscribes the same plan in multiple times then system do not the restrict the user for buying same plan in multiple plans.

**Comment by Zalasanjay** [comment]
It is valid to create the same plan in multiple times and there is no restriction on creating same plan in current system so, that is allowed.

**Comment by qajha** [comment]
As per developer comment and current scenario the same plan purchase the multiple times by same user.
