### ISSUE TITLE
QA-Subscription List-When user buying the multiple plan then in Subscription list is not showing in ascending order

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/flowz-product-#65]
When user buying the multiple plans then in Subscription list is not showing in ascending order the last subscription should always be showing in list sequence number.

**Comment by qajha** [comment]
created subscription data is showing any where.

**Comment by qajha** [comment]
Issue is resolved now in QA server

**Comment by Zalasanjay** [comment]
There was changes in subscription back-end and that is merged.

**Comment by qajha** [comment]
Issue is resolved now in QA server
