### ISSUE TITLE
QA-Subscription Create Plan-1. Validity and value 10Days data is overlap 2.When user disable the all Plan and select the Subscription List from login dashboard window system should be showing warning message "No Subscription is Available" or any other message.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/flowz-product-#84]
1.Validity and value 10Days data is overlap

2.When user disable the all Plan and select the Subscription List from login dashboard window system should be showing warning message "No Subscription is Available" or any other message.

3.When admin user have only enable the two plan then in subscription List the two plan data alignment is not proper.
![subscriptionlist](https://user-images.githubusercontent.com/36195435/36477711-2e774b86-1728-11e8-8e7c-70fc65f26c9e.png)

**Comment by chiragob** [comment]
ui changed

**Comment by qajha** [comment]
Issue is resolved now and new UI is changed
