### ISSUE TITLE
QA-Subscription Setting-When user create the Plan and buying the Plan and then user change the some setting in create plan section and those changes is not reflect and user have to create the new plan again.

### ISSUE THREAD

**Issue by qajha** [FlowzPlatform/flowz-product-#94]
When user create the Plan and buying the Plan and then user change the some setting in create plan section and those changes is not reflect and user have to create the new plan again.

**Comment by chiragob** [comment]
once user subscribe the plan after some updates on created plan, subscribe user will not getting those updates. they have to buy same plan again.

for e.g in mobile operator create one 10 mbps plan and user subscribe this plan  and after sometime mobile operator update these plan to 15 mbps. so subscribed user will not getting those update they have to update this plan

we will discuss if any issue

**Comment by qajha** [comment]
As per chirag comment I have closed this ticket
